### ISSUE TITLE
Example Images

### ISSUE THREAD

**Issue by affeltranger** [ioridev/LiDAR-Depth-Map-Capture-for-iOS#1]
Hi

I'm currently looking into depth map capturing / surface reconstruction techniques. Your project looks like it does exactly what I would want to do to run some tests with the I-Phone. Unfortunately I don't have a Mac at the moment to build the project and try for myself. So before I go and buy a computer for that, I wanted to ask if you could upload some example images you took with the app.
Ideally of something small like for example a tea cup, sunglasses or maybe a keyboard and mouse.

Thanks!
All the best,
Philipp

**Comment by ioridev** [comment]
https://github.com/ioridev/LiDAR-Depth-Map-Capture-for-iOS/tree/main/samples

A sample of the shooting data has been added to the repository.

**Comment by ioridev** [comment]
I will consider releasing this app to the App Store if you need it.

**Comment by ioridev** [comment]
https://apps.apple.com/us/app/depth-camera-raw/id6557075309
